
export const proyectos = [ {
    id: 1,
    img: "./assets/Img/magenta.png",
    name: "Magenta",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://cristianmozetich.github.io/Magenta/",
    year: "2022",
    tech: "Html - Css - Scss - Bootstrap",
},
{
    id: 2,
    img: "./assets/Img/houseofmusic.png",
    name: "House Of Music",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://cristianmozetich.github.io/ProyectoFinal-Mozetich/",
    year: "2023",
    tech: "Html - Css - JavaScript - Bootstrap",
},
{
    id: 3,
    img: "./assets/Img/art&wine.png",
    name: "Art & Wine",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://43200-react.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js - Vite - Firebase - Bootstrap",
},
{
    id: 4,
    img: "./assets/Img/tateti.png",
    name: "Tic Tac Toe ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://superlative-raindrop-91350e.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js - Vite",
},
];
