
export const proyectos = [
{
    id: 1,
    //img: "./assets/Img/imc2.jpg",
    name: "IMC",
    desc: "App para calcular tu índice de masa corporal (IMC) ingresando tu peso y altura.",
    web: "https://indice-m-corp.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js",
},
{
    id: 2,
    //img: "./assets/Img/art_wine.jpg",
    name: "Art & Wine",
    desc: "App que simula una tienda de vinos, puedes agregar al carrito y comprar.",
    web: "https://art-wine.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js - Vite - Firebase - Bootstrap",
},
{
    id: 3,
    //img: "./assets/Img/tateti.jpg",
    name: "Tic Tac Toe ",
    desc: "Juego Tic-Tac-Toe",
    web: "https://ta-te-ti-91.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js - Vite",
},
{
    id: 4,
    //img: "./assets/Img/music.jpg",
    name: "House Of Music",
    desc: "Tienda de instrumentos músicales, puedes agregar al carrito, comprar y disfrutar un blog de lectura.",
    web: "https://house-of-music.netlify.app/",
    year: "2023",
    tech: "Html - Css - JavaScript - Bootstrap",
},
{
    id: 5,
    //img: "./assets/Img/magenta.jpg",
    name: "Magenta",
    desc: "Página web de un comercio dedicado a la fabricación, venta de alianzas y relojes.",
    web: "https://cristianmozetich.github.io/Magenta/",
    year: "2022",
    tech: "Html - Css - Scss - Bootstrap",
},
];
