
export const proyectos = [
{
    id: 1,
    img: "./assets/Img/imc.jpg",
    name: "IMC",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://indice-m-corp.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js",
},
{
    id: 2,
    img: "./assets/Img/art&wine.png",
    name: "Art & Wine",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://art-wine.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js - Vite - Firebase - Bootstrap",
},
{
    id: 3,
    img: "./assets/Img/tateti.png",
    name: "Tic Tac Toe ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://ta-te-ti-91.netlify.app/",
    year: "2023",
    tech: "Html - Css - React Js - Vite",
},
{
    id: 4,
    img: "./assets/Img/houseofmusic.png",
    name: "House Of Music",
    web: "https://cristianmozetich.github.io/ProyectoFinal-Mozetich/",
    year: "2023",
    tech: "Html - Css - JavaScript - Bootstrap",
},
{
    id: 5,
    img: "./assets/Img/magenta.png",
    name: "Magenta",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, possimus.",
    web: "https://cristianmozetich.github.io/Magenta/",
    year: "2022",
    tech: "Html - Css - Scss - Bootstrap",
},
];
